"$schema" = 'https://starship.rs/config-schema.json'

# [系统层] [目录层] [版本控制层] [语言层] [环境/容器层] [时间/耗时层]
# >>>
palette = '{{ . }}'

format = """
[](color_bg_os)\
$os\
$username\
[](fg:color_bg_os bg:color_bg_path)\
$directory\
[](fg:color_bg_path bg:color_bg_git)\
$git_branch\
$git_status\
$git_commit\
$git_state\
[](fg:color_bg_git bg:color_bg_lang)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_bg_lang bg:color_bg_env)\
$conda\
$docker_context\
$kubernetes\
$pixi\
[](fg:color_bg_env bg:color_bg_time)\
$time\
$cmd_duration\
[ ](fg:color_bg_time)\
$line_break\
$character"""

# ╭──────────────────────────────────────────────────────────╮
# │ 系统层                                                   │
# ╰──────────────────────────────────────────────────────────╯
[os]
disabled = false
style = 'bg:color_bg_os fg:color_fg_os'
format = '[$symbol]($style)'

[os.symbols]
Windows = '󰍲'
Ubuntu = '󰕈'
SUSE = ''
Raspbian = '󰐿'
Mint = '󰣭'
Macos = '󰀵'
Manjaro = ''
Linux = '󰌽'
Gentoo = '󰣨'
Fedora = '󰣛'
Alpine = ''
Amazon = ''
Android = ''
AOSC = ''
Arch = '󰣇'
Artix = '󰣇'
EndeavourOS = ''
CentOS = ''
Debian = '󰣚'
Redhat = '󱄛'
RedHatEnterprise = '󱄛'
Pop = ''
Zorin = ''

[username]
show_always = true
style_user = 'bg:color_bg_os fg:color_fg_os'
style_root = 'bg:color_bg_os fg:color_bg_path'
format = '[ $user ]($style)'

# ╭──────────────────────────────────────────────────────────╮
# │ 目录层                                                   │
# ╰──────────────────────────────────────────────────────────╯
[directory]
style = 'bg:color_bg_path fg:color_fg_path'
read_only_style = 'bg:color_bg_path fg:color_bg_env'
read_only = '󰌾 '
format = '[ $path ]($style)[$read_only]($read_only_style)'
truncation_length = 3
truncation_symbol = '…/'

# ╭──────────────────────────────────────────────────────────╮
# │ 版本控制层                                               │
# ╰──────────────────────────────────────────────────────────╯
[git_branch]
disabled = false
symbol = ''
style = 'bg:color_bg_git fg:color_fg_git'
format = '[ $symbol $branch ]($style)'

[git_status]
disabled = false
style = 'bg:color_bg_git fg:color_fg_git'
format = '[$all_status$ahead_behind ]($style)'
conflicted  = ' ' # 正在合并/变基, 出现冲突未解决
stashed     = ' ' # 本地有 git stash 存起来的条目
deleted     = ' ' # 跟踪的文件被删除未 commit
renamed     = ' 󰑕' # 跟踪的文件重命名未 commit
modified    = ' ' # 跟踪的文件内容改动未 commit
typechanged = ' 󰕁' # 文件类型改变(e.g. 普通 -> 可执行)
staged      = ' $count:' # 改动已 git add 进暂存区
untracked   = ' $count:' # 新建文件未跟踪
diverged    = '  $ahead_count $behind_count' # 本地既领先又落后(分叉)
ahead       = ' $count:' # 触发条件: commit 但没 push
behind      = ' $count:' # 触发条件: 远程仓库有更新且本地尚未合并
up_to_date  = ' '        # 触发条件: ahead 和 behind 无触发时

[git_commit]
disabled = false
style = 'bg:color_bg_git fg:color_fg_git'
format = '[  $hash $tag]($style)'
commit_hash_length = 5
tag_symbol = ' '
only_detached = false
tag_disabled = false

[git_state]
disabled = false
style = 'bg:color_bg_git fg:color_fg_git'
format = '[ $state$progress_current/$progress_total ]($style)'
merge = ''  # 无步进信息
bisect = '' # 无步进信息
rebase       = ' '
revert       = '󰕌 '
cherry_pick  = ' '
am           = ' '
am_or_rebase = ' or  '

# ╭──────────────────────────────────────────────────────────╮
# │ 语言层                                                   │
# ╰──────────────────────────────────────────────────────────╯
[nodejs]
symbol = ''
style = 'bg:color_bg_lang fg:color_fg_lang'
format = '[ $symbol $version ]($style)'

[c]
symbol = ' '
style = 'bg:color_bg_lang fg:color_fg_lang'
format = '[ $symbol $version ]($style)'

[cpp]
symbol = ' '
style = 'bg:color_bg_lang fg:color_fg_lang'
format = '[ $symbol $version ]($style)'

[rust]
symbol = ''
style = 'bg:color_bg_lang fg:color_fg_lang'
format = '[ $symbol $version ]($style)'

[golang]
symbol = ''
style = 'bg:color_bg_lang fg:color_fg_lang'
format = '[ $symbol $version ]($style)'

[php]
symbol = ''
style = 'bg:color_bg_lang fg:color_fg_lang'
format = '[ $symbol $version ]($style)'

[java]
symbol = ''
style = 'bg:color_bg_lang fg:color_fg_lang'
format = '[ $symbol $version ]($style)'

[kotlin]
symbol = ''
style = 'bg:color_bg_lang fg:color_fg_lang'
format = '[ $symbol $version ]($style)'

[haskell]
symbol = ''
style = 'bg:color_bg_lang fg:color_fg_lang'
format = '[ $symbol $version ]($style)'

[python]
symbol = ''
style = 'bg:color_bg_lang fg:color_fg_lang'
python_binary = [['uv', 'run', '--no-python-downloads', 'python'], 'python', 'python3', 'python3', '.pixi/envs/default/bin/python']
format = '[ $symbol $version ]($style)'

# ╭──────────────────────────────────────────────────────────╮
# │ 环境/容器层                                              │
# ╰──────────────────────────────────────────────────────────╯
[kubernetes]
disabled = false
symbol = '☸ '
style = 'bg:color_bg_env fg:color_fg_env'
format = '[ $symbol $context:$namespace ]($style)'
detect_env_vars = ['KUBECONFIG']
detect_files = ['k8s', '.k8s', '.kube']

[docker_context]
disabled = false
symbol = '🐳'
style = 'bg:color_bg_env fg:color_fg_env'
format = '[ $symbol( $context) ]($style)'

[conda]
disabled = false
symbol = '🅒'
ignore_base = false
style = 'bg:color_bg_env fg:color_fg_env'
format = '[ $symbol( $environment) ]($style)'

[pixi]
disabled = false
symbol = '🧚'
style = 'bg:color_bg_env fg:color_fg_env'
format = '[ $symbol $version ]($style)'

# ╭──────────────────────────────────────────────────────────╮
# │ 时间/耗时层                                              │
# ╰──────────────────────────────────────────────────────────╯
[time]
disabled = false
time_format = '%R'
style = 'fg:color_fg_time bg:color_bg_time'
format = '[  $time ]($style)'

[cmd_duration]
disabled = false
min_time = 500
show_milliseconds = true
style = 'fg:color_fg_time bg:color_bg_time'
format = '[ $duration]($style)'

# ╭──────────────────────────────────────────────────────────╮
# │ 提示符符号                                               │
# ╰──────────────────────────────────────────────────────────╯
[line_break]
disabled = false

[character]
success_symbol = '[❯](fg:bold green)[❯](fg:bold orange)[❯](fg:bold red)'
error_symbol   = '[❯](fg:bold red)[❯](fg:bold red)[❯](fg:bold red)'

# ╭──────────────────────────────────────────────────────────╮
# │ 调色盘                                                   │
# ╰──────────────────────────────────────────────────────────╯
{{ include (joinPath ".chezmoitemplates" "starship" "palettes" (printf "%s.toml" .)) -}}