[palettes.autumn_hues] # https://www.design-seeds.com/2024/08/autumn-hues.html
color_bg_os   = '#E1C59D'
color_bg_path = '#CF8E4A'
color_bg_git  = '#80543E'
color_bg_lang = '#2C3562'
color_bg_env  = '#455F9E'
color_bg_time = '#A9AB8E'

color_fg_os   = '#040e38'
color_fg_path = '#040e38'
color_fg_git  = '#fbf1c7'
color_fg_lang = '#fbf1c7'
color_fg_env  = '#fbf1c7'
color_fg_time = '#040e38'