[palettes.mustache] # https://colorleap.app/time/1800
color_bg_os   = '#F36B3C'
color_bg_path = '#EBD7BC'
color_bg_git  = '#C9B099'
color_bg_lang = '#84674C'
color_bg_env  = '#3E3832'
color_bg_time = '#AB3855'

color_fg_os   = '#040e38'
color_fg_path = '#040e38'
color_fg_git  = '#040e38'
color_fg_lang = '#fbf1c7'
color_fg_env  = '#fbf1c7'
color_fg_time = '#fbf1c7'