[palettes.still_hues_5] # https://www.design-seeds.com/2024/08/still-hues_5.html
color_bg_os   = '#47757C'
color_bg_path = '#304A6C'
color_bg_git  = '#1B3247'
color_bg_lang = '#9C2A27'
color_bg_env  = '#B2612D'
color_bg_time = '#D8CEB5'

color_fg_os   = '#fbf1c7'
color_fg_path = '#fbf1c7'
color_fg_git  = '#fbf1c7'
color_fg_lang = '#fbf1c7'
color_fg_env  = '#fbf1c7'
color_fg_time = '#040e38'