[palettes.tribes] # https://colorleap.app/time/1930
color_bg_os   = '#38526E'
color_bg_path = '#DAC9AF'
color_bg_git  = '#C19C82'
color_bg_lang = '#AE7757'
color_bg_env  = '#6C4838'
color_bg_time = '#AB3855'

color_fg_os   = '#fbf1c7'
color_fg_path = '#040e38'
color_fg_git  = '#040e38'
color_fg_lang = '#fbf1c7'
color_fg_env  = '#fbf1c7'
color_fg_time = '#fbf1c7'