[general]
live_config_reload = true

[font]
normal = { family = "Maple Mono NF CN", style = "Regular" }
bold = { family = "Maple Mono NF CN", style = "Bold" }
italic = { family = "Maple Mono NF CN", style = "Italic" }
size = 11

[window]
dimensions = { columns = 80, lines = 25 }
opacity = 0.8
dynamic_title = false

[scrolling]
history = 12345

[selection]
save_to_clipboard = true

[terminal]
{{- if eq .chezmoi.os "windows" }}
shell = { program = "pwsh", args = ['-nologo'] }
{{- else if eq .chezmoi.os "linux" }}
shell = { program = "bash", args = [] }
{{- end }}

[mouse]
bindings = [
    { mouse = "Right", mods = "None", action = "Paste" }
]

[keyboard]
bindings = [
    { key = "m", mods = "Alt", action = "ToggleMaximized" },
    { key = "b", mods = "Control|Shift", action = "Minimize" },
    { key = "w", mods = "Alt", action = "Quit" },
]

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "e", mods = "Alt" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"


# ╭──────────────────────────────────────────────────────────╮
# │ seashells                                                │
# ╰──────────────────────────────────────────────────────────╯

[colors.primary]
background = '#061923'
foreground = '#e5c49e'

[colors.cursor]
text = '#061822'
cursor = '#feaf3c'

[colors.selection]
text = '#ffe9d7'
background = '#265b75'

# Normal colors
[colors.normal]
black = '#1d485f'
red = '#db662d'
green = '#008eab'
yellow = '#feaf3c'
blue = '#255a62'
magenta = '#77dbf4'
cyan = '#5fb1c2'
white = '#e5c49e'

# Bright colors
[colors.bright]
black = '#545d65'
red = '#dd998a'
green = '#739da8'
yellow = '#fedaae'
blue = '#0bc7e3'
magenta = '#c6e8f1'
cyan = '#97b9c0'
white = '#ffe9d7'
